name = "omw"
compatibility_date = "2024-05-26"

[build]
command = "bash build.sh"

main = "worker.js"

[assets]
directory = "output/wwwroot"
not_found_handling = "single-page-application"
include = ["**/*"]

